### ISSUE TITLE
if diff has space in folderName/fileName in filePath then parsed filename is wrong

### ISSUE THREAD

**Issue by future-pirate-king** [rtfpessoa/diff2html#387] opened 2021-05-24 12:39 UTC
### Step -1: Before filling an issue check out troubleshooting section

- Go to [README.md#Troubleshooting](https://github.com/rtfpessoa/diff2html#troubleshooting)

### Step 0: Describe your environment

- OS: ubuntu 20.04 LTS
- diff2html version: 3.4.3
- Using diff2html directly or using diff2html-ui helper: using both
- Extra flags: **\_**

### Step 1: Describe the problem:
when user creates a folder or file with name some which has space in it then the parsed output of unified diff is giving wrong fileName

#### Steps to reproduce:

1. use can use unified diff which has space in folder name or file name and check parsed output

#### diff example:

```diff
diff --git a/notebooks/Untitled Folder/untitled.txt b/notebooks/Untitled Folder/untitled.txt\nnew file mode 100644\nindex 0000000..e69de29\ndiff --git a/notebooks/new.txt b/notebooks/new1.txt\nsimilarity index 83%\nrename from notebooks/new.txt\nrename to notebooks/new1.txt\nindex 0dea293..fe4d7e2 100644\n--- a/notebooks/new.txt\n+++ b/notebooks/new1.txt\n@@ -1,2 +1,2 @@\n Text to test git backend functionality.\n-new li\n\\ No newline at end of file\n+new line\n\\ No newline at end of file\ndiff --git a/notebooks/untitled1.txt b/notebooks/untitled1.txt\nnew file mode 100644\nindex 0000000..3e5126c\n--- /dev/null\n+++ b/notebooks/untitled1.txt\n@@ -0,0 +1 @@\n+new\n\\ No newline at end of file\n
```

#### Observed Results:

- What happened? This could be a description, log output, etc.
​​
addedLines: 0
blocks: Array []
checksumAfter: "e69de29"
checksumBefore: "0000000"
deletedLines: 0
isGitDiff: true
isNew: true
newFileMode: "100644"
newName: "Folder/untitled.txt"
oldName: "notebooks/Untitled Folder/untitled.txt b/notebooks/Untitled"

#### Expected Results:

- What did you expect to happen?

newName: "notebooks/Untitled Folder/untitled.txt"
oldName: "notebooks/Untitled Folder/untitled.txt"

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by rtfpessoa** [comment] 2021-05-25 16:32
@future-pirate-king where did you get that diff from?
I am asking because it is not a valid unified diff, since the lines with `---` and `+++` are missing in the first file.

**Comment by future-pirate-king** [comment] 2021-05-25 16:38
so this is generated using these commands

1. first we stage the changes using -> git add .
2. then diff using -> git diff --cached

**Comment by rtfpessoa** [comment] 2021-06-03 22:52
That is indeed a very interesting corner case.

I think it is impossible to solve in a simple way.
Since it is not a valid unified diff, due to the lines with `---` and `+++` and since the only header available does not have a clear separator between the file paths, it is very error prone to know the names using it.

Do you have any suggestions?

**Comment by future-pirate-king** [comment] 2021-06-13 08:53
currently this line of code is parsing the filenames for this case
https://github.com/rtfpessoa/diff2html/blob/73ab5ba05059dd476fbbb0b4b1f50a005aae38b7/src/diff-parser.ts#L279

if we change the regex to 
`^diff --git "?(a\/.+)"? "?(b\/.+)"?`

seems to work. @rtfpessoa what do you think ?

**Comment by rtfpessoa** [comment] 2021-06-21 19:27
That is a not going to work if the first path has a ` b/` in it. But probably it is not worse than it is right now.

**Comment by future-pirate-king** [comment] 2021-06-27 12:00
yes @rtfpessoa , that was just an example. if we know the possible prefixes we can create regex like this
`^diff --git "?([abiwco]\/.+)"? "?([abiwco]\/.+)"?`

**Comment by rtfpessoa** [comment] 2021-07-09 21:30
The problem is not the types of prefixes if if the paths have spaces and a path like this will parse incorrectly still:
`diff --git a/my/amazing b/path.js b/new/different/path.js`

**Comment by rtfpessoa** [comment] 2021-07-09 21:40
Anyway since it does not stay worse than what it is now I went ahead and merged the update. Let me know how it goes.

**Closed** 2021-07-09 21:39 UTC

**Comment by rtfpessoa** [comment] 2021-07-09 21:48
Released as version `3.4.7`

**Comment by karansaraswat19** [comment] 2024-07-16 09:52
Hello @rtfpessoa 
I feel this issue is still there. I use the `parse` method and it appends `\t` at the end and destroys the value. Can you please check this?
<img width="1226" alt="Screenshot 2024-07-16 at 3 18 58 PM" src="https://github.com/user-attachments/assets/e2f66f69-116b-46fc-a680-25e5f50af17a">

**Comment by rtfpessoa** [comment] 2024-07-20 20:31
Can you provide an example?
