### ISSUE TITLE
How do I localize "File without changes" text?

### ISSUE THREAD

**Issue by pinkcloud98** [rtfpessoa/diff2html#247] opened 2019-12-03 20:16 UTC
**Describe the bug**
How do I localize "File without changes" text?
Is there anyway to pass a locale?

**To Reproduce**
When there is no change, "File without changes" text is not localized into the browser's current locale setting.

**Expected behavior**
"File without changes" text should be localized to Chinese if Chinese is the current language set in the browser.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux, Mac]
 - Browser [e.g. Firefox, Chrome, Safari]

**Additional context**

**Comment by rtfpessoa** [comment] 2023-08-11 19:37
Not sure how this issue got lost, but to achieve this we would either need to introduce the concept of localization, or provide custom templates with chinese as a language.

**Comment by rtfpessoa** [comment] 2023-08-11 19:41
Duplicate of https://github.com/rtfpessoa/diff2html/issues/428

**Closed by rtfpessoa** 2023-08-11 19:41 UTC
